#define eng_width 80
#define eng_height 80
#define eng_x_hot 39
#define eng_y_hot 39
#define flaps0_width 64
#define flaps0_height 32
#define flaps0_x_hot 4
#define flaps0_y_hot 25
#define flaps1_width 64
#define flaps1_height 32
#define flaps1_x_hot -1
#define flaps1_y_hot -1
#define flaps2_width 64
#define flaps2_height 32
#define flaps2_x_hot -1
#define flaps2_y_hot -1
#define flaps3_width 64
#define flaps3_height 32
#define flaps3_x_hot -1
#define flaps3_y_hot -1
#define gearDown_width 25
#define gearDown_height 25
#define gearTran_width 25
#define gearTran_height 25
#define gearUp_width 25
#define gearUp_height 25
#define handleDn_width 32
#define handleDn_height 75
#define handleUp_width 32
#define handleUp_height 75
