CFLAGS= -g -Wall 
MAINOBJS=fgmain.o fgload.o fgkbd.o fgscreen.o fggrx.o fgslew.o \
	fgtimer.o fgini.o fggeom.o fgevent.o fgpause.o \
	fgrand.o fgpalet.o fgbars.o fgclock.o fgfont.o \
	../modules/aircraft/flight.so ../modules/hud/fghud.so

fgmain: $(MAINOBJS)
	gcc $(CFLAGS) -o fgmain $(MAINOBJS) -L/usr/X11R6/lib -lm -lX11 -lXext -ldl

