CFLAGS= -g -Wall 
MAINOBJS=fgmain.o fgload.o fgkbd.o fgscreen.o fggrx.o fgslew.o \
	fgtimer.o fgini.o fggeom.o fgevent.o fgpause.o \
	fgrand.o fgpalet.o fgbars.o fgclock.o fgfont.o dll.o


fgmain: $(MAINOBJS)
	gcc $(CFLAGS) -o fgmain.exe $(MAINOBJS) -lm -lalleg 

