.SUFFIXES: .exe .lib .a .dll .so .sa .o .obj .c .s .cc .res .rc .def
RM=/bin/rm
CP=/bin/cp
CC=gcc
FGDEFS=-DUSE_FB
FGLIBS=-lm -lcurses -ltermcap -ldl
LIBDIRS=
SYS_DEFINES=-D__sparc__ -D__GNUC__
CFLAGS= -g -Wall $(FGDEFS) 
OBJ_SUFFIX=o
EXECUTABLE=fgmain
EXTRA_OBJS=
RESOURCE=
LINK.RESOURCE=
ICON=

include makefile.inc

